import 'package:flutter/material.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static const List<Locale> supportedLocales = <Locale>[
    Locale('en'),
    Locale('fr'),
    Locale('es'),
    Locale('ru'),
    Locale('uk'),
    Locale('bg'),
    Locale('pl'),
    Locale('pt'),
    Locale('ja'),
    Locale('zh', 'TW'),
    Locale('zh', 'CN'),
    Locale('ko'),
    Locale('ar'),
  ];

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ??
        AppLocalizations(const Locale('en'));
  }

  String get profile => _t('profile');
  String get calendar => _t('calendar');
  String get account => _t('account');
  String get friends => _t('friends');
  String get notes => _t('notes');
  String get points => _t('points');
  String get rewards => _t('rewards');
  String get daily => _t('daily');
  String get weekly => _t('weekly');
  String get schedule => _t('schedule');
  String get freeTimeThisWeek => _t('freeTimeThisWeek');
  String get preferences => _t('preferences');
  String get progress => _t('progress');
  String get support => _t('support');
  String get help => _t('help');
  String get settings => _t('settings');
  String get editProfile => _t('editProfile');
  String get manageProfile => _t('manageProfile');
  String get personalInfo => _t('personalInfo');
  String get manageInfo => _t('manageInfo');
  String get notificationSettings => _t('notificationSettings');
  String get alertsReminders => _t('alertsReminders');
  String get darkMode => _t('darkMode');
  String get off => _t('off');
  String get changePassword => _t('changePassword');
  String get updatePassword => _t('updatePassword');
  String get twoFactor => _t('twoFactor');
  String get extraSecurity => _t('extraSecurity');
  String get logOut => _t('logOut');
  String get deleteAccount => _t('deleteAccount');
  String get totalPoints => _t('totalPoints');
  String get activities => _t('activities');
  String get history => _t('history');
  String get chores => _t('chores');
  String get work => _t('work');
  String get freeTime => _t('freeTime');
  String get timeOff => _t('timeOff');
  String get levelUp => _t('levelUp');
  String get pointsWord => _t('pointsWord');
  String get pointsShort => _t('pointsShort');
  String get coins => _t('coins');
  String get levelShort => _t('levelShort');
  String get level => _t('level');
  String get search => _t('search');
  String get myList => _t('myList');
  String get pending => _t('pending');
  String get searchContacts => _t('searchContacts');
  String get noContactsFound => _t('noContactsFound');
  String get noMatchingContacts => _t('noMatchingContacts');
  String get noFriendsYet => _t('noFriendsYet');
  String get noPendingRequests => _t('noPendingRequests');
  String get friendRequestSent => _t('friendRequestSent');
  String get friendRequestAlreadyPending => _t('friendRequestAlreadyPending');
  String get incoming => _t('incoming');
  String get requested => _t('requested');
  String get tryAgain => _t('tryAgain');
  String get language => _t('language');
  String get security => _t('security');

  String levelLabel(int level) {
    return _format('levelLabel', {'level': '$level'});
  }

  String levelPointsLabel(int level, String pointsLabel) {
    return _format('levelPointsLabel', {
      'level': '$level',
      'points': pointsLabel,
    });
  }

  String pointsWithValue(String value) {
    return _format('pointsWithValue', {
      'value': value,
      'points': pointsWord,
    });
  }

  String actionPressed(String label) {
    return _format('actionPressed', {'label': label});
  }

  String _t(String key) {
    final localeKey = _localeKey(locale);
    final values = _localizedValues[localeKey] ?? _localizedValues['en']!;
    return values[key] ?? _localizedValues['en']![key] ?? key;
  }

  String _format(String key, Map<String, String> values) {
    var template = _t(key);
    values.forEach((placeholder, value) {
      template = template.replaceAll('{$placeholder}', value);
    });
    return template;
  }

  String _localeKey(Locale locale) {
    if (locale.languageCode == 'zh' &&
        locale.countryCode != null &&
        locale.countryCode!.isNotEmpty) {
      return 'zh_${locale.countryCode}';
    }
    return locale.languageCode;
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return AppLocalizations.supportedLocales.any((supported) =>
        supported.languageCode == locale.languageCode &&
        (supported.countryCode == null ||
            supported.countryCode == locale.countryCode));
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

const Map<String, Map<String, String>> _localizedValues = {
  'en': {
    'profile': 'Profile',
    'calendar': 'Calendar',
    'account': 'Account',
    'friends': 'Friends',
    'notes': 'Notes',
    'points': 'Points',
    'rewards': 'Rewards',
    'daily': 'Daily',
    'weekly': 'Weekly',
    'schedule': 'Schedule',
    'freeTimeThisWeek': 'Free time this week',
    'preferences': 'Preferences',
    'progress': 'Progress',
    'support': 'Support',
    'help': 'Help',
    'settings': 'Settings',
    'editProfile': 'Edit Profile',
    'manageProfile': 'Manage your profile',
    'personalInfo': 'Personal Info',
    'manageInfo': 'Manage your info',
    'notificationSettings': 'Notification Settings',
    'alertsReminders': 'Alerts and reminders',
    'darkMode': 'Dark Mode',
    'off': 'Off',
    'changePassword': 'Change Password',
    'updatePassword': 'Update your password',
    'twoFactor': 'Two-Factor Authentication',
    'extraSecurity': 'Add extra security',
    'logOut': 'Log Out',
    'deleteAccount': 'Delete Account',
    'totalPoints': 'Total Points',
    'activities': 'Activities',
    'history': 'History',
    'chores': 'Chores',
    'work': 'Work',
    'freeTime': 'Free time',
    'timeOff': 'Time off',
    'levelUp': 'Level up!',
    'pointsWord': 'points',
    'pointsShort': 'pts',
    'coins': 'coins',
    'levelShort': 'Lvl',
    'level': 'Level',
    'search': 'Search',
    'myList': 'My List',
    'pending': 'Pending',
    'searchContacts': 'Search contacts',
    'noContactsFound': 'No contacts found on this device.',
    'noMatchingContacts': 'No matching contacts.',
    'noFriendsYet': 'No friends yet.',
    'noPendingRequests': 'No pending requests.',
    'friendRequestSent': 'Friend request sent.',
    'friendRequestAlreadyPending': 'Friend request already pending.',
    'incoming': 'Incoming',
    'requested': 'Requested',
    'tryAgain': 'Try again',
    'language': 'Language',
    'security': 'Security',
    'levelLabel': 'Level {level}',
    'levelPointsLabel': 'Level {level} · {points}',
    'pointsWithValue': '{value} {points}',
    'actionPressed': '{label} pressed',
  },
  'fr': {
    'profile': 'Profil',
    'calendar': 'Calendrier',
    'account': 'Compte',
    'friends': 'Amis',
    'notes': 'Notes',
    'points': 'Points',
    'rewards': 'Récompenses',
    'daily': 'Quotidien',
    'weekly': 'Hebdomadaire',
    'schedule': 'Planning',
    'freeTimeThisWeek': 'Temps libre cette semaine',
    'preferences': 'Préférences',
    'progress': 'Progrès',
    'support': 'Support',
    'help': 'Aide',
    'settings': 'Paramètres',
    'editProfile': 'Modifier le profil',
    'manageProfile': 'Gérer votre profil',
    'personalInfo': 'Infos personnelles',
    'manageInfo': 'Gérer vos informations',
    'notificationSettings': 'Paramètres de notification',
    'alertsReminders': 'Alertes et rappels',
    'darkMode': 'Mode sombre',
    'off': 'Désactivé',
    'changePassword': 'Changer le mot de passe',
    'updatePassword': 'Mettre à jour votre mot de passe',
    'twoFactor': 'Authentification à deux facteurs',
    'extraSecurity': 'Ajouter une sécurité supplémentaire',
    'logOut': 'Déconnexion',
    'deleteAccount': 'Supprimer le compte',
    'totalPoints': 'Total des points',
    'activities': 'Activités',
    'history': 'Historique',
    'chores': 'Tâches ménagères',
    'work': 'Travail',
    'freeTime': 'Temps libre',
    'timeOff': 'Congés',
    'levelUp': 'Niveau supérieur !',
    'pointsWord': 'points',
    'pointsShort': 'pts',
    'coins': 'pièces',
    'levelShort': 'Niv',
    'level': 'Niveau',
    'search': 'Rechercher',
    'myList': 'Ma liste',
    'pending': 'En attente',
    'searchContacts': 'Rechercher des contacts',
    'noContactsFound': 'Aucun contact trouvé sur cet appareil.',
    'noMatchingContacts': 'Aucun contact correspondant.',
    'noFriendsYet': 'Pas encore d\'amis.',
    'noPendingRequests': 'Aucune demande en attente.',
    'friendRequestSent': 'Demande d\'ami envoyée.',
    'friendRequestAlreadyPending': 'Demande d\'ami déjà en attente.',
    'incoming': 'Entrante',
    'requested': 'Demandée',
    'tryAgain': 'Réessayer',
    'language': 'Langue',
    'security': 'Sécurité',
    'levelLabel': 'Niveau {level}',
    'levelPointsLabel': 'Niveau {level} · {points}',
    'pointsWithValue': '{value} {points}',
    'actionPressed': '{label} sélectionné',
  },
  'es': {
    'profile': 'Perfil',
    'calendar': 'Calendario',
    'account': 'Cuenta',
    'friends': 'Amigos',
    'notes': 'Notas',
    'points': 'Puntos',
    'rewards': 'Recompensas',
    'daily': 'Diario',
    'weekly': 'Semanal',
    'schedule': 'Horario',
    'freeTimeThisWeek': 'Tiempo libre esta semana',
    'preferences': 'Preferencias',
    'progress': 'Progreso',
    'support': 'Soporte',
    'help': 'Ayuda',
    'settings': 'Configuración',
    'editProfile': 'Editar perfil',
    'manageProfile': 'Administra tu perfil',
    'personalInfo': 'Información personal',
    'manageInfo': 'Administra tu información',
    'notificationSettings': 'Configuración de notificaciones',
    'alertsReminders': 'Alertas y recordatorios',
    'darkMode': 'Modo oscuro',
    'off': 'Desactivado',
    'changePassword': 'Cambiar contraseña',
    'updatePassword': 'Actualizar tu contraseña',
    'twoFactor': 'Autenticación de dos factores',
    'extraSecurity': 'Agregar seguridad extra',
    'logOut': 'Cerrar sesión',
    'deleteAccount': 'Eliminar cuenta',
    'totalPoints': 'Puntos totales',
    'activities': 'Actividades',
    'history': 'Historial',
    'chores': 'Tareas',
    'work': 'Trabajo',
    'freeTime': 'Tiempo libre',
    'timeOff': 'Días libres',
    'levelUp': '¡Sube de nivel!',
    'pointsWord': 'puntos',
    'pointsShort': 'pts',
    'coins': 'monedas',
    'levelShort': 'Nvl',
    'level': 'Nivel',
    'search': 'Buscar',
    'myList': 'Mi lista',
    'pending': 'Pendiente',
    'searchContacts': 'Buscar contactos',
    'noContactsFound': 'No se encontraron contactos en este dispositivo.',
    'noMatchingContacts': 'No hay contactos coincidentes.',
    'noFriendsYet': 'Aún no hay amigos.',
    'noPendingRequests': 'No hay solicitudes pendientes.',
    'friendRequestSent': 'Solicitud de amistad enviada.',
    'friendRequestAlreadyPending': 'La solicitud de amistad ya está pendiente.',
    'incoming': 'Recibida',
    'requested': 'Solicitada',
    'tryAgain': 'Intentar de nuevo',
    'language': 'Idioma',
    'security': 'Seguridad',
    'levelLabel': 'Nivel {level}',
    'levelPointsLabel': 'Nivel {level} · {points}',
    'pointsWithValue': '{value} {points}',
    'actionPressed': '{label} seleccionado',
  },
  'ru': {
    'profile': 'Профиль',
    'calendar': 'Календарь',
    'account': 'Аккаунт',
    'friends': 'Друзья',
    'notes': 'Заметки',
    'points': 'Очки',
    'rewards': 'Награды',
    'daily': 'День',
    'weekly': 'Неделя',
    'schedule': 'Расписание',
    'freeTimeThisWeek': 'Свободное время на этой неделе',
    'preferences': 'Предпочтения',
    'progress': 'Прогресс',
    'support': 'Поддержка',
    'help': 'Помощь',
    'settings': 'Настройки',
    'editProfile': 'Редактировать профиль',
    'manageProfile': 'Управляйте профилем',
    'personalInfo': 'Личные данные',
    'manageInfo': 'Управляйте данными',
    'notificationSettings': 'Настройки уведомлений',
    'alertsReminders': 'Оповещения и напоминания',
    'darkMode': 'Тёмный режим',
    'off': 'Выкл.',
    'changePassword': 'Сменить пароль',
    'updatePassword': 'Обновить пароль',
    'twoFactor': 'Двухфакторная аутентификация',
    'extraSecurity': 'Добавить дополнительную защиту',
    'logOut': 'Выйти',
    'deleteAccount': 'Удалить аккаунт',
    'totalPoints': 'Всего очков',
    'activities': 'Активности',
    'history': 'История',
    'chores': 'Домашние дела',
    'work': 'Работа',
    'freeTime': 'Свободное время',
    'timeOff': 'Отгул',
    'levelUp': 'Повышение уровня!',
    'pointsWord': 'очков',
    'pointsShort': 'очк.',
    'coins': 'монет',
    'levelShort': 'Ур.',
    'level': 'Уровень',
    'search': 'Поиск',
    'myList': 'Мой список',
    'pending': 'В ожидании',
    'searchContacts': 'Поиск контактов',
    'noContactsFound': 'Контакты на устройстве не найдены.',
    'noMatchingContacts': 'Нет подходящих контактов.',
    'noFriendsYet': 'Друзей пока нет.',
    'noPendingRequests': 'Нет ожидающих запросов.',
    'friendRequestSent': 'Запрос дружбы отправлен.',
    'friendRequestAlreadyPending': 'Запрос дружбы уже ожидает.',
    'incoming': 'Входящий',
    'requested': 'Отправлен',
    'tryAgain': 'Повторить',
    'language': 'Язык',
    'security': 'Безопасность',
    'levelLabel': 'Уровень {level}',
    'levelPointsLabel': 'Уровень {level} · {points}',
    'pointsWithValue': '{value} {points}',
    'actionPressed': '{label} нажато',
  },
  'uk': {
    'profile': 'Профіль',
    'calendar': 'Календар',
    'account': 'Обліковий запис',
    'friends': 'Друзі',
    'notes': 'Нотатки',
    'points': 'Бали',
    'rewards': 'Нагороди',
    'daily': 'Щодня',
    'weekly': 'Щотижня',
    'schedule': 'Розклад',
    'freeTimeThisWeek': 'Вільний час цього тижня',
    'preferences': 'Налаштування',
    'progress': 'Прогрес',
    'support': 'Підтримка',
    'help': 'Допомога',
    'settings': 'Налаштування',
    'editProfile': 'Редагувати профіль',
    'manageProfile': 'Керуйте профілем',
    'personalInfo': 'Особиста інформація',
    'manageInfo': 'Керуйте інформацією',
    'notificationSettings': 'Налаштування сповіщень',
    'alertsReminders': 'Сповіщення та нагадування',
    'darkMode': 'Темний режим',
    'off': 'Вимкнено',
    'changePassword': 'Змінити пароль',
    'updatePassword': 'Оновити пароль',
    'twoFactor': 'Двофакторна автентифікація',
    'extraSecurity': 'Додати додатковий захист',
    'logOut': 'Вийти',
    'deleteAccount': 'Видалити обліковий запис',
    'totalPoints': 'Всього балів',
    'activities': 'Активності',
    'history': 'Історія',
    'chores': 'Домашні справи',
    'work': 'Робота',
    'freeTime': 'Вільний час',
    'timeOff': 'Відпустка',
    'levelUp': 'Підвищення рівня!',
    'pointsWord': 'балів',
    'pointsShort': 'б.',
    'coins': 'монет',
    'levelShort': 'Рів.',
    'level': 'Рівень',
    'search': 'Пошук',
    'myList': 'Мій список',
    'pending': 'Очікує',
    'searchContacts': 'Пошук контактів',
    'noContactsFound': 'На пристрої немає контактів.',
    'noMatchingContacts': 'Немає відповідних контактів.',
    'noFriendsYet': 'Друзів ще немає.',
    'noPendingRequests': 'Немає запитів у черзі.',
    'friendRequestSent': 'Запит у друзі надіслано.',
    'friendRequestAlreadyPending': 'Запит у друзі вже очікує.',
    'incoming': 'Вхідний',
    'requested': 'Надіслано',
    'tryAgain': 'Спробувати ще раз',
    'language': 'Мова',
    'security': 'Безпека',
    'levelLabel': 'Рівень {level}',
    'levelPointsLabel': 'Рівень {level} · {points}',
    'pointsWithValue': '{value} {points}',
    'actionPressed': '{label} натиснуто',
  },
  'bg': {
    'profile': 'Профил',
    'calendar': 'Календар',
    'account': 'Акаунт',
    'friends': 'Приятели',
    'notes': 'Бележки',
    'points': 'Точки',
    'rewards': 'Награди',
    'daily': 'Дневно',
    'weekly': 'Седмично',
    'schedule': 'График',
    'freeTimeThisWeek': 'Свободно време тази седмица',
    'preferences': 'Предпочитания',
    'progress': 'Напредък',
    'support': 'Поддръжка',
    'help': 'Помощ',
    'settings': 'Настройки',
    'editProfile': 'Редактиране на профила',
    'manageProfile': 'Управлявайте профила си',
    'personalInfo': 'Лична информация',
    'manageInfo': 'Управлявайте информацията си',
    'notificationSettings': 'Настройки на известията',
    'alertsReminders': 'Известия и напомняния',
    'darkMode': 'Тъмен режим',
    'off': 'Изкл.',
    'changePassword': 'Смяна на парола',
    'updatePassword': 'Обновете паролата',
    'twoFactor': 'Двуфакторна автентикация',
    'extraSecurity': 'Добавете допълнителна защита',
    'logOut': 'Изход',
    'deleteAccount': 'Изтриване на акаунта',
    'totalPoints': 'Общо точки',
    'activities': 'Дейности',
    'history': 'История',
    'chores': 'Домашни задачи',
    'work': 'Работа',
    'freeTime': 'Свободно време',
    'timeOff': 'Почивка',
    'levelUp': 'Ниво нагоре!',
    'pointsWord': 'точки',
    'pointsShort': 'т.',
    'coins': 'монети',
    'levelShort': 'Ниво',
    'level': 'Ниво',
    'search': 'Търсене',
    'myList': 'Моят списък',
    'pending': 'В изчакване',
    'searchContacts': 'Търсене на контакти',
    'noContactsFound': 'Няма намерени контакти на това устройство.',
    'noMatchingContacts': 'Няма съвпадащи контакти.',
    'noFriendsYet': 'Нямате приятели.',
    'noPendingRequests': 'Няма чакащи заявки.',
    'friendRequestSent': 'Заявката за приятелство е изпратена.',
    'friendRequestAlreadyPending':
        'Заявката за приятелство вече е в изчакване.',
    'incoming': 'Входяща',
    'requested': 'Изпратена',
    'tryAgain': 'Опитай отново',
    'language': 'Език',
    'security': 'Сигурност',
    'levelLabel': 'Ниво {level}',
    'levelPointsLabel': 'Ниво {level} · {points}',
    'pointsWithValue': '{value} {points}',
    'actionPressed': '{label} натиснато',
  },
  'pl': {
    'profile': 'Profil',
    'calendar': 'Kalendarz',
    'account': 'Konto',
    'friends': 'Znajomi',
    'notes': 'Notatki',
    'points': 'Punkty',
    'rewards': 'Nagrody',
    'daily': 'Dzienny',
    'weekly': 'Tygodniowy',
    'schedule': 'Harmonogram',
    'freeTimeThisWeek': 'Czas wolny w tym tygodniu',
    'preferences': 'Preferencje',
    'progress': 'Postęp',
    'support': 'Wsparcie',
    'help': 'Pomoc',
    'settings': 'Ustawienia',
    'editProfile': 'Edytuj profil',
    'manageProfile': 'Zarządzaj profilem',
    'personalInfo': 'Dane osobowe',
    'manageInfo': 'Zarządzaj informacjami',
    'notificationSettings': 'Ustawienia powiadomień',
    'alertsReminders': 'Alerty i przypomnienia',
    'darkMode': 'Tryb ciemny',
    'off': 'Wył.',
    'changePassword': 'Zmień hasło',
    'updatePassword': 'Zaktualizuj hasło',
    'twoFactor': 'Uwierzytelnianie dwuskładnikowe',
    'extraSecurity': 'Dodaj dodatkowe zabezpieczenie',
    'logOut': 'Wyloguj',
    'deleteAccount': 'Usuń konto',
    'totalPoints': 'Suma punktów',
    'activities': 'Aktywności',
    'history': 'Historia',
    'chores': 'Obowiązki domowe',
    'work': 'Praca',
    'freeTime': 'Czas wolny',
    'timeOff': 'Urlop',
    'levelUp': 'Poziom wyżej!',
    'pointsWord': 'punktów',
    'pointsShort': 'pkt',
    'coins': 'monety',
    'levelShort': 'Poziom',
    'level': 'Poziom',
    'search': 'Szukaj',
    'myList': 'Moja lista',
    'pending': 'Oczekujące',
    'searchContacts': 'Szukaj kontaktów',
    'noContactsFound': 'Brak kontaktów na tym urządzeniu.',
    'noMatchingContacts': 'Brak pasujących kontaktów.',
    'noFriendsYet': 'Brak znajomych.',
    'noPendingRequests': 'Brak oczekujących próśb.',
    'friendRequestSent': 'Zaproszenie wysłane.',
    'friendRequestAlreadyPending': 'Zaproszenie już oczekuje.',
    'incoming': 'Przychodzące',
    'requested': 'Wysłane',
    'tryAgain': 'Spróbuj ponownie',
    'language': 'Język',
    'security': 'Bezpieczeństwo',
    'levelLabel': 'Poziom {level}',
    'levelPointsLabel': 'Poziom {level} · {points}',
    'pointsWithValue': '{value} {points}',
    'actionPressed': '{label} wybrano',
  },
  'pt': {
    'profile': 'Perfil',
    'calendar': 'Calendário',
    'account': 'Conta',
    'friends': 'Amigos',
    'notes': 'Notas',
    'points': 'Pontos',
    'rewards': 'Recompensas',
    'daily': 'Diário',
    'weekly': 'Semanal',
    'schedule': 'Agenda',
    'freeTimeThisWeek': 'Tempo livre nesta semana',
    'preferences': 'Preferências',
    'progress': 'Progresso',
    'support': 'Suporte',
    'help': 'Ajuda',
    'settings': 'Configurações',
    'editProfile': 'Editar perfil',
    'manageProfile': 'Gerencie seu perfil',
    'personalInfo': 'Informações pessoais',
    'manageInfo': 'Gerencie suas informações',
    'notificationSettings': 'Configurações de notificações',
    'alertsReminders': 'Alertas e lembretes',
    'darkMode': 'Modo escuro',
    'off': 'Desativado',
    'changePassword': 'Alterar senha',
    'updatePassword': 'Atualize sua senha',
    'twoFactor': 'Autenticação de dois fatores',
    'extraSecurity': 'Adicione segurança extra',
    'logOut': 'Sair',
    'deleteAccount': 'Excluir conta',
    'totalPoints': 'Total de pontos',
    'activities': 'Atividades',
    'history': 'Histórico',
    'chores': 'Tarefas domésticas',
    'work': 'Trabalho',
    'freeTime': 'Tempo livre',
    'timeOff': 'Folga',
    'levelUp': 'Subiu de nível!',
    'pointsWord': 'pontos',
    'pointsShort': 'pts',
    'coins': 'moedas',
    'levelShort': 'Nível',
    'level': 'Nível',
    'search': 'Buscar',
    'myList': 'Minha lista',
    'pending': 'Pendente',
    'searchContacts': 'Buscar contatos',
    'noContactsFound': 'Nenhum contato encontrado neste dispositivo.',
    'noMatchingContacts': 'Nenhum contato correspondente.',
    'noFriendsYet': 'Nenhum amigo ainda.',
    'noPendingRequests': 'Nenhuma solicitação pendente.',
    'friendRequestSent': 'Solicitação de amizade enviada.',
    'friendRequestAlreadyPending': 'Solicitação de amizade já pendente.',
    'incoming': 'Recebida',
    'requested': 'Solicitada',
    'tryAgain': 'Tentar novamente',
    'language': 'Idioma',
    'security': 'Segurança',
    'levelLabel': 'Nível {level}',
    'levelPointsLabel': 'Nível {level} · {points}',
    'pointsWithValue': '{value} {points}',
    'actionPressed': '{label} selecionado',
  },
  'ja': {
    'profile': 'プロフィール',
    'calendar': 'カレンダー',
    'account': 'アカウント',
    'friends': '友達',
    'notes': 'ノート',
    'points': 'ポイント',
    'rewards': '報酬',
    'daily': '日次',
    'weekly': '週間',
    'schedule': 'スケジュール',
    'freeTimeThisWeek': '今週の空き時間',
    'preferences': '設定',
    'progress': '進捗',
    'support': 'サポート',
    'help': 'ヘルプ',
    'settings': '設定',
    'editProfile': 'プロフィールを編集',
    'manageProfile': 'プロフィールを管理',
    'personalInfo': '個人情報',
    'manageInfo': '情報を管理',
    'notificationSettings': '通知設定',
    'alertsReminders': 'アラートとリマインダー',
    'darkMode': 'ダークモード',
    'off': 'オフ',
    'changePassword': 'パスワードを変更',
    'updatePassword': 'パスワードを更新',
    'twoFactor': '二要素認証',
    'extraSecurity': '追加のセキュリティを追加',
    'logOut': 'ログアウト',
    'deleteAccount': 'アカウントを削除',
    'totalPoints': '合計ポイント',
    'activities': 'アクティビティ',
    'history': '履歴',
    'chores': '家事',
    'work': '仕事',
    'freeTime': '自由時間',
    'timeOff': '休暇',
    'levelUp': 'レベルアップ！',
    'pointsWord': 'ポイント',
    'pointsShort': 'pt',
    'coins': 'コイン',
    'levelShort': 'Lv',
    'level': 'レベル',
    'search': '検索',
    'myList': 'マイリスト',
    'pending': '保留中',
    'searchContacts': '連絡先を検索',
    'noContactsFound': 'この端末に連絡先がありません。',
    'noMatchingContacts': '一致する連絡先がありません。',
    'noFriendsYet': 'まだ友達がいません。',
    'noPendingRequests': '保留中のリクエストはありません。',
    'friendRequestSent': '友達申請を送信しました。',
    'friendRequestAlreadyPending': '友達申請は既に保留中です。',
    'incoming': '受信中',
    'requested': '送信済み',
    'tryAgain': '再試行',
    'language': '言語',
    'security': 'セキュリティ',
    'levelLabel': 'レベル {level}',
    'levelPointsLabel': 'レベル {level} · {points}',
    'pointsWithValue': '{value} {points}',
    'actionPressed': '{label} を選択しました',
  },
  'zh_TW': {
    'profile': '個人檔案',
    'calendar': '行事曆',
    'account': '帳戶',
    'friends': '好友',
    'notes': '筆記',
    'points': '點數',
    'rewards': '獎勵',
    'daily': '每日',
    'weekly': '每週',
    'schedule': '行程',
    'freeTimeThisWeek': '本週空閒時間',
    'preferences': '偏好設定',
    'progress': '進度',
    'support': '支援',
    'help': '說明',
    'settings': '設定',
    'editProfile': '編輯個人檔案',
    'manageProfile': '管理個人檔案',
    'personalInfo': '個人資訊',
    'manageInfo': '管理資訊',
    'notificationSettings': '通知設定',
    'alertsReminders': '提醒與通知',
    'darkMode': '深色模式',
    'off': '關閉',
    'changePassword': '更改密碼',
    'updatePassword': '更新密碼',
    'twoFactor': '兩步驟驗證',
    'extraSecurity': '新增額外安全性',
    'logOut': '登出',
    'deleteAccount': '刪除帳戶',
    'totalPoints': '總點數',
    'activities': '活動',
    'history': '歷史',
    'chores': '家務',
    'work': '工作',
    'freeTime': '空閒時間',
    'timeOff': '休假',
    'levelUp': '升級！',
    'pointsWord': '點',
    'pointsShort': '點',
    'coins': '金幣',
    'levelShort': '等級',
    'level': '等級',
    'search': '搜尋',
    'myList': '我的清單',
    'pending': '待處理',
    'searchContacts': '搜尋聯絡人',
    'noContactsFound': '此裝置沒有聯絡人。',
    'noMatchingContacts': '沒有符合的聯絡人。',
    'noFriendsYet': '尚無好友。',
    'noPendingRequests': '沒有待處理的請求。',
    'friendRequestSent': '已送出好友邀請。',
    'friendRequestAlreadyPending': '好友邀請已在待處理中。',
    'incoming': '來自',
    'requested': '已請求',
    'tryAgain': '重試',
    'language': '語言',
    'security': '安全性',
    'levelLabel': '等級 {level}',
    'levelPointsLabel': '等級 {level} · {points}',
    'pointsWithValue': '{value} {points}',
    'actionPressed': '已選擇 {label}',
  },
  'zh_CN': {
    'profile': '个人资料',
    'calendar': '日历',
    'account': '账户',
    'friends': '好友',
    'notes': '笔记',
    'points': '积分',
    'rewards': '奖励',
    'daily': '每日',
    'weekly': '每周',
    'schedule': '日程',
    'freeTimeThisWeek': '本周空闲时间',
    'preferences': '偏好设置',
    'progress': '进度',
    'support': '支持',
    'help': '帮助',
    'settings': '设置',
    'editProfile': '编辑资料',
    'manageProfile': '管理个人资料',
    'personalInfo': '个人信息',
    'manageInfo': '管理信息',
    'notificationSettings': '通知设置',
    'alertsReminders': '提醒与通知',
    'darkMode': '深色模式',
    'off': '关闭',
    'changePassword': '更改密码',
    'updatePassword': '更新密码',
    'twoFactor': '双重验证',
    'extraSecurity': '添加额外安全性',
    'logOut': '退出登录',
    'deleteAccount': '删除账户',
    'totalPoints': '总积分',
    'activities': '活动',
    'history': '历史',
    'chores': '家务',
    'work': '工作',
    'freeTime': '空闲时间',
    'timeOff': '休假',
    'levelUp': '升级！',
    'pointsWord': '积分',
    'pointsShort': '分',
    'coins': '金币',
    'levelShort': '等级',
    'level': '等级',
    'search': '搜索',
    'myList': '我的列表',
    'pending': '待处理',
    'searchContacts': '搜索联系人',
    'noContactsFound': '此设备没有联系人。',
    'noMatchingContacts': '没有匹配的联系人。',
    'noFriendsYet': '暂无好友。',
    'noPendingRequests': '没有待处理的请求。',
    'friendRequestSent': '已发送好友请求。',
    'friendRequestAlreadyPending': '好友请求已在等待中。',
    'incoming': '收到',
    'requested': '已请求',
    'tryAgain': '重试',
    'language': '语言',
    'security': '安全',
    'levelLabel': '等级 {level}',
    'levelPointsLabel': '等级 {level} · {points}',
    'pointsWithValue': '{value} {points}',
    'actionPressed': '已选择{label}',
  },
  'ko': {
    'profile': '프로필',
    'calendar': '캘린더',
    'account': '계정',
    'friends': '친구',
    'notes': '노트',
    'points': '포인트',
    'rewards': '보상',
    'daily': '일일',
    'weekly': '주간',
    'schedule': '일정',
    'freeTimeThisWeek': '이번 주 여유 시간',
    'preferences': '환경설정',
    'progress': '진행 상황',
    'support': '지원',
    'help': '도움말',
    'settings': '설정',
    'editProfile': '프로필 편집',
    'manageProfile': '프로필 관리',
    'personalInfo': '개인 정보',
    'manageInfo': '정보 관리',
    'notificationSettings': '알림 설정',
    'alertsReminders': '알림 및 미리 알림',
    'darkMode': '다크 모드',
    'off': '꺼짐',
    'changePassword': '비밀번호 변경',
    'updatePassword': '비밀번호 업데이트',
    'twoFactor': '2단계 인증',
    'extraSecurity': '추가 보안 설정',
    'logOut': '로그아웃',
    'deleteAccount': '계정 삭제',
    'totalPoints': '총 포인트',
    'activities': '활동',
    'history': '기록',
    'chores': '집안일',
    'work': '업무',
    'freeTime': '여가 시간',
    'timeOff': '휴가',
    'levelUp': '레벨 업!',
    'pointsWord': '포인트',
    'pointsShort': 'pt',
    'coins': '코인',
    'levelShort': 'Lv',
    'level': '레벨',
    'search': '검색',
    'myList': '내 목록',
    'pending': '보류 중',
    'searchContacts': '연락처 검색',
    'noContactsFound': '이 기기에 연락처가 없습니다.',
    'noMatchingContacts': '일치하는 연락처가 없습니다.',
    'noFriendsYet': '아직 친구가 없습니다.',
    'noPendingRequests': '대기 중인 요청이 없습니다.',
    'friendRequestSent': '친구 요청을 보냈습니다.',
    'friendRequestAlreadyPending': '친구 요청이 이미 대기 중입니다.',
    'incoming': '수신',
    'requested': '요청됨',
    'tryAgain': '다시 시도',
    'language': '언어',
    'security': '보안',
    'levelLabel': '레벨 {level}',
    'levelPointsLabel': '레벨 {level} · {points}',
    'pointsWithValue': '{value} {points}',
    'actionPressed': '{label} 선택됨',
  },
  'ar': {
    'profile': 'الملف الشخصي',
    'calendar': 'التقويم',
    'account': 'الحساب',
    'friends': 'الأصدقاء',
    'notes': 'الملاحظات',
    'points': 'النقاط',
    'rewards': 'المكافآت',
    'daily': 'يومي',
    'weekly': 'أسبوعي',
    'schedule': 'الجدول',
    'freeTimeThisWeek': 'وقت الفراغ هذا الأسبوع',
    'preferences': 'التفضيلات',
    'progress': 'التقدم',
    'support': 'الدعم',
    'help': 'المساعدة',
    'settings': 'الإعدادات',
    'editProfile': 'تعديل الملف الشخصي',
    'manageProfile': 'إدارة ملفك الشخصي',
    'personalInfo': 'المعلومات الشخصية',
    'manageInfo': 'إدارة معلوماتك',
    'notificationSettings': 'إعدادات الإشعارات',
    'alertsReminders': 'التنبيهات والتذكيرات',
    'darkMode': 'الوضع الداكن',
    'off': 'إيقاف',
    'changePassword': 'تغيير كلمة المرور',
    'updatePassword': 'تحديث كلمة المرور',
    'twoFactor': 'المصادقة الثنائية',
    'extraSecurity': 'إضافة أمان إضافي',
    'logOut': 'تسجيل الخروج',
    'deleteAccount': 'حذف الحساب',
    'totalPoints': 'إجمالي النقاط',
    'activities': 'الأنشطة',
    'history': 'السجل',
    'chores': 'الأعمال المنزلية',
    'work': 'العمل',
    'freeTime': 'وقت الفراغ',
    'timeOff': 'إجازة',
    'levelUp': 'ترقية المستوى!',
    'pointsWord': 'نقاط',
    'pointsShort': 'ن.',
    'coins': 'عملات',
    'levelShort': 'مستوى',
    'level': 'المستوى',
    'search': 'بحث',
    'myList': 'قائمتي',
    'pending': 'قيد الانتظار',
    'searchContacts': 'البحث في جهات الاتصال',
    'noContactsFound': 'لم يتم العثور على جهات اتصال على هذا الجهاز.',
    'noMatchingContacts': 'لا توجد جهات اتصال مطابقة.',
    'noFriendsYet': 'لا يوجد أصدقاء بعد.',
    'noPendingRequests': 'لا توجد طلبات معلقة.',
    'friendRequestSent': 'تم إرسال طلب صداقة.',
    'friendRequestAlreadyPending': 'طلب الصداقة قيد الانتظار بالفعل.',
    'incoming': 'وارد',
    'requested': 'مطلوب',
    'tryAgain': 'حاول مرة أخرى',
    'language': 'اللغة',
    'security': 'الأمان',
    'levelLabel': 'المستوى {level}',
    'levelPointsLabel': 'المستوى {level} · {points}',
    'pointsWithValue': '{value} {points}',
    'actionPressed': 'تم اختيار {label}',
  },
};
